core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    AxxountView,
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('account/', AxxountView.as_view(), name='account'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

djecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from cloudinary.models import CloudinaryField
from django_countries.fields import CountryField


CATEGORY_CHOICES = (
    ('S', 'Smoke'),
)

LABEL_CHOICES = (
    ('T', 'Top'),
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


SUBSCRIBTION_CHOICES = (
    ('oneweek', (
        ('pay', 10.70),
    )),
    ('twoweeks', (
        ('pay', 18.42),
    )),
    ('onemonth', (
        ('pay', 95.30),
    )),
    ('threemonths', (
        ('pay', 170),
    )),
    ('sixmonths', (
        ('pay', 182),
    )),
    ('oneyear', (
        ('pay', 279),
    )),
)
SUBSCRIBTION_DAY_CHOICES = (
    ('oneweek', (
        ('day', 7),
    )),
    ('twoweeks', (
        ('day', 14),
    )),
    ('onemonth', (
        ('day', 30),
    )),
    ('threemonths', (
        ('day', 91),
    )),
    ('sixmonths', (
        ('day', 183),
    )),
    ('oneyear', (
        ('day', 365),
    )),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class UserAccount(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    country = models.CharField(max_length=5000, blank=True, null=True)
    state = models.CharField(max_length=5000, blank=True, null=True)
    phone = models.CharField(max_length=5000, blank=True, null=True)
    address = models.CharField(max_length=5000, blank=True, null=True)
    tranxid = models.CharField(max_length=5000, blank=True, null=True)
    filename = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = CloudinaryField('image')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="breadcrumb">
	<div class="container">
		<div class="breadcrumb-inner">
			<ul class="list-inline list-unstyled">
				<li><a href="{% url 'core:home' %}">Home</a></li>
				<li class='active'>Checkout</li>
			</ul>
		</div><!-- /.breadcrumb-inner -->
	</div><!-- /.container -->
</div><!-- /.breadcrumb -->

						<!-- checkout-step-01  -->
<div class="panel panel-default checkout-step-01">
    <div class="container wow fadeIn">
      <h2 class="my-5 h2 text-center">Checkout form</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">
            <form class="card-body">
              {% csrf_token %}

              <h3>Shipping address</h3>

              <div class='hideable_shipping_form'>

                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address' class='form-control' />
                  <label for="shipping_address" class="">Address</label>
                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2' class='form-control' />
                  <label for="shipping_address2" class="">Address 2 (optional)</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.shipping_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="shipping_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>
                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="same_billing_address" id="same_billing_address">
                  <label class="custom-control-label" for="same_billing_address">Billing address is the same as my shipping address</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
                  <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
                </div>

              </div>

              {% if default_shipping_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
                <label class="custom-control-label" for="use_default_shipping">Use default shipping address: {{ default_shipping_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}

              <hr>

           

           <h3>Payment option</h3>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  
                  
                </div>
                {% endfor %}
              </div>

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" >Continue to checkout</button>

            </form>

          </div>

        </div>

        <div class="col-md-4 mb-4">
          {% include "order_snippet.html" %}
        </div>

      </div>
      <br>
      <br>
      <br>

    </div>
</div>

{% endblock content %}

templates/navbar.html
{% load static %}
{% load cart_template_tag %}
<body class="cnt-home"  style="background-color: #f0fa96;">
    <!-- ============================================== HEADER ============================================== -->
    <header class="header-style-1"> 
      
      <!-- ============================================== TOP MENU ============================================== -->
      
      <!-- /.header-top --> 
      <!-- ============================================== TOP MENU : END ============================================== -->
      <div class="main-header">
        <div class="container">
          <div class="row">
            <div class="col-xs-13 col-sm-12 col-md-3 logo-holder"> 
              <!-- ============================================================= LOGO ============================================================= -->
              <div class="logo"> <a href="{% url 'core:home' %}"> <img src="{% static 'images/logo.png' %}" alt="logo" height="90" width="120"> </a> 
                <p style="color:#f0fa96; ">We buy and deliver all type of hard drugs</p></div><!-- /.logo --> 
              <!-- ============================================================= LOGO : END ============================================================= --> </div>
            <!-- /.logo-holder -->
            
              <!-- /.contact-row --> 
              <!-- ============================================================= SEARCH AREA ============================================================= -->
              
              <!-- /.search-area --> 
              <!-- ============================================================= SEARCH AREA : END ============================================================= --> 
            <!-- /.top-search-holder -->
            
            <div class=" animate-dropdown top-cart-row"> 
              <!-- ============================================================= SHOPPING CART DROPDOWN ============================================================= -->
              
              <div class="dropdown dropdown-cart"> <a href="{% url 'core:order-summary' %}" class="dropdown-toggle lnk-cart" data-toggle="dropdown">
                <div class="items-cart-inner">
                  <div class="basket">
                  <div class="basket-item-count"><span class="count">{{ request.user|cart_item_count }}</span></div>
                  <div class="total-price-basket"> <span class="lbl" >Shopping Cart</span><span class="value"></span> </div>
                  </div>
                </div>
                </a>
                
              </div>
              <!-- /.dropdown-cart --> 
            </div>
          </div>
              <!-- ============================================================= SHOPPING CART DROPDOWN : END============================================================= --> </div>
            <!-- /.top-cart-row --> 
          </div>
          <!-- /.row --> 
          
        </div>
        <!-- /.container --> 
        
      </div>
      <!-- /.main-header --> 
        <!-- /.main-header --> 
        <!-- ============================================== NAVBAR ============================================== -->
  <div class="header-nav animate-dropdown" style=" background-color: #0C8241; ">
    <div class="container"> 
      <div class="yamm navbar navbar-default" role="navigation" >
        <div class="navbar-header">
       <button data-target="#mc-horizontal-menu-collapse" data-toggle="collapse" class="navbar-toggle collapsed" type="button"> 
       <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        </div>
        <div class="nav-bg-class" >
          <div class="navbar-collapse collapse" id="mc-horizontal-menu-collapse">
            <div class="nav-outer">
              <ul class="nav navbar-nav">
               <li class="dropdown navbar-right"> <a href="#" class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown">Drugs</a>
                  <ul class="dropdown-menu pages">
                    <li>
                      <div class="yamm-content">
                        <div class="row">
                          <div class="col-xs-12 col-menu">
                            <ul class="links">
                              <li class="dropdown menu-item"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon fa fa-envira"></i>Ketamine</a> 
                                <li class="dropdown menu-item"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon fa fa-envira"></i>Meth</a> 
                                <li class="dropdown menu-item"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon fa fa-envira"></i>MDMA</a> 
                                <li class="dropdown menu-item"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon fa fa-envira"></i>Adderall</a> 
                                <li class="dropdown menu-item"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon fa fa-envira"></i>Broom-dragonfly</a> 
                                <li class="dropdown menu-item"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon fa fa-envira"></i>Oxys</a> 
                                <li class="dropdown menu-item"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon fa fa-envira"></i>Dilaudid</a> 
                                <li class="dropdown menu-item"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon fa fa-envira"></i>Mescaline</a> 
                                <li class="dropdown menu-item"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon fa fa-envira"></i>Mushroom</a> 
                                <li class="dropdown menu-item"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon fa fa-envira"></i>Bath salts</a>
                                <li class="dropdown menu-item"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon fa fa-envira"></i>Cortisone</a> 
                                <li class="dropdown menu-item"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon fa fa-envira"></i>Toradol</a>
                                <li class="dropdown menu-item"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon fa fa-envira"></i>Aspirin crack</a> 
                                <li class="dropdown menu-item"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon fa fa-envira"></i>Flint stone gummies</a>
                                <li class="dropdown menu-item"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon fa fa-envira"></i>Nicotine</a> 
                               
                                <li class="dropdown menu-item"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon fa fa-envira"></i>Home and Garden</a> 
                                  <!-- /.dropdown-menu --> </li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </li>
                  </ul>
                </li>
                {% if request.user.is_authenticated %}
                <li class="chdropdowneck navbar-right"><a href="{% url 'account_logout' %}"><span>Logout</span></a></li>
                <li class="dropdown navbar-right"><a href="{% url 'core:order-summary' %}"><span>My Cart</span></a></li>
                <li class="dropdown navbar-right"><a href="{% url 'core:account' %}"><span>My Dashboard</span></a></li>
                {% else %}
                <li class="dropdown navbar-right"><a href="{% url 'account_login' %}"><span>Login</span></a></li>
                <li class="dropdown navbar-right"><a href="{% url 'account_signup' %}"><span>Create Account</span></a></li>
                {% endif %}
                <li class="dropdown navbar-right"><a href="{% url 'core:home' %}"><span>Home</span></a></li>
                

                
                 
                
               
              </ul>
              <!-- /.navbar-nav -->
              <div class="clearfix"></div>
            </div>
            <!-- /.nav-outer --> 
          </div>
          <!-- /.navbar-collapse --> 
          
        </div>
        <!-- /.nav-bg-class --> 
      </div>
      <!-- /.navbar-default --> 
    </div>
    <!-- /.container-class --> 
    
  </div>
  <!-- /.header-nav --> 
  <!-- ============================================== NAVBAR : END ============================================== -->   
 
  <!-- /.header-nav --> 
  <!-- ============================================== NAVBAR : END ============================================== --> 
</header>

templates/order_snippet.html
<div class="col-md-12 mb-6">
    <h4 class="d-flex justify-content-between align-items-center mb-4">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">${{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>${{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/product.html
{% extends "base.html" %}

{% block content %}

<div class="breadcrumb">
	<div class="container">
		<div class="breadcrumb-inner">
			<ul class="list-inline list-unstyled">
				<li><a href="{% url 'core:home' %}">Home</a></li>
				<li class='active'>Floral Print Buttoned</li>
			</ul>
		</div><!-- /.breadcrumb-inner -->
	</div><!-- /.container -->
</div><!-- /.breadcrumb -->
  
    <div class="detail-block">
<div class="row">
        
       <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 gallery-holder">
<div class="product-item-holder size-big single-product-gallery small-gallery">

<div id="owl-single-product">
    <div class="single-product-gallery-item" id="slide1">
        <a data-lightbox="image-1" data-title="Gallery" href="{{ object.image.url  }">
            <img class="img-responsive" alt="" src="{{ object.image.url  }}" />
        </a>
    </div><!-- /.single-product-gallery-item -->

    <div class="single-product-gallery-item" id="slide2">
        <a data-lightbox="image-1" data-title="Gallery" href="{{ object.image.url  }">
            <img class="img-responsive" alt="" src="{{ object.image.url  }}" />
        </a>
    </div><!-- /.single-product-gallery-item -->

    <div class="single-product-gallery-item" id="slide3">
        <a data-lightbox="image-1" data-title="Gallery" href="{{ object.image.url  }">
            <img class="img-responsive" alt="" src="{{ object.image.url  }}" />
        </a>
    </div><!-- /.single-product-gallery-item -->

    <div class="single-product-gallery-item" id="slide4">
        <a data-lightbox="image-1" data-title="Gallery" href="{{ object.image.url  }">
            <img class="img-responsive" alt="" src="{{ object.image.url  }}" />
        </a>
    </div><!-- /.single-product-gallery-item -->

    <div class="single-product-gallery-item" id="slide5">
        <a data-lightbox="image-1" data-title="Gallery" href="{{ object.image.url  }">
            <img class="img-responsive" alt="" src="{{ object.image.url  }}" />
        </a>
    </div><!-- /.single-product-gallery-item -->

    <div class="single-product-gallery-item" id="slide6">
        <a data-lightbox="image-1" data-title="Gallery" href="{{ object.image.url  }">
            <img class="img-responsive" alt="" src="{{ object.image.url  }}" />
        </a>
    </div><!-- /.single-product-gallery-item -->

    <div class="single-product-gallery-item" id="slide7">
        <a data-lightbox="image-1" data-title="Gallery" href="{{ object.image.url  }">
            <img class="img-responsive" alt="" src="{{ object.image.url  }}" />
        </a>
    </div><!-- /.single-product-gallery-item -->

    <div class="single-product-gallery-item" id="slide8">
        <a data-lightbox="image-1" data-title="Gallery" href="{{ object.image.url  }">
            <img class="img-responsive" alt="" src="{{ object.image.url  }}" />
        </a>
    </div><!-- /.single-product-gallery-item -->

    <div class="single-product-gallery-item" id="slide9">
        <a data-lightbox="image-1" data-title="Gallery" href="{{ object.image.url  }">
            <img class="img-responsive" alt="" src="{{ object.image.url  }}" />
        </a>
    </div><!-- /.single-product-gallery-item -->

</div><!-- /.single-product-slider -->



</div><!-- /.single-product-gallery -->
</div><!-- /.gallery-holder -->        			
  <div class='col-sm-12 col-md-8 col-lg-8 product-info-block'>
    <div class="product-info">
      <h1 class="name">{{ object.title }}</h1>
      
      <div class="rating-reviews m-t-20">
        <div class="row">
                        <div class="col-lg-12">
          <div class="pull-left">
            <div class="rating rateit-small"></div>
          </div>
          <div class="pull-left">
            <div class="reviews">
              <a href="#" class="lnk">(13 Reviews)</a>
            </div>
          </div>
                            </div>
        </div><!-- /.row -->		
      </div><!-- /.rating-reviews -->

      <div class="stock-container info-container m-t-10">
        <div class="row">
                        <div class="col-lg-12">
          <div class="pull-left">
            <div class="stock-box">
              <span class="value">Category :</span>
            </div>	
          </div>
          <div class="pull-left">
            <div class="stock-box">
              <span class="value">{{ object.get_category_display }}</span>
            </div>	
          </div>
                            </div>
        </div><!-- /.row -->	
      </div><!-- /.stock-container -->

      <div class="description-container m-t-20">
        <p>{{ object.description }}</p>
      </div><!-- /.description-container -->

      <div class="price-container info-container m-t-30">
        <div class="row">
          

          <div class="col-sm-6 col-xs-6">
            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>${{ object.price }}</del>
              </span>
              <span>${{ object.discount_price }}</span>
              {% else %}
              <span>${{ object.price }}</span>
              {% endif %}
            </p>
          </div>

          <div class="col-sm-6 col-xs-6">
            <div class="favorite-button m-t-5">
              <a class="btn btn-primary" data-toggle="tooltip" data-placement="right" title="Wishlist" href="#">
                  <i class="fa fa-heart"></i>
              </a>
              <a class="btn btn-primary" data-toggle="tooltip" data-placement="right" title="Add to Compare" href="#">
                 <i class="fa fa-signal"></i>
              </a>
              <a class="btn btn-primary" data-toggle="tooltip" data-placement="right" title="E-mail" href="#">
                  <i class="fa fa-envelope"></i>
              </a>
            </div>
          </div>

        </div><!-- /.row -->
      </div><!-- /.price-container -->

      <div class="quantity-container info-container">
        <div class="row">
          
          
          <div class="add-btn">
            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary"><i class="fa fa-shopping-cart inner-right-vs"></i> ADD TO CART</a>
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger"><i class="fa fa-shopping-cart inner-right-vs"></i> REMOVE FROM CART</a>
          </div>

          
        </div><!-- /.row -->
      </div><!-- /.quantity-container -->

      
    </div>
      

      
    </div><!-- /.product-info -->
  </div><!-- /.col-sm-7 -->
</div><!-- /.row -->



{% endblock content %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}

templates/scripts.html
{% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>
<script type="text/javascript">
  function CopyText() {
  var text = document.getElementById('sm1')
  text.select();
  document.execCommand('copy')
}
</script>